olddb/config/routes.rb
RoutenDb::Application.routes.draw do
  get "index/new"

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "/boulders/:id/showcomments" => "boulders#showcomments"

  root :to => "index#new"
  
  match "/boulders/:id/deactivate" => "boulders#deactivate"
  match "/boulders/:id/tick/:type/:event_id/:user_id" => "boulders#tick"
  match "/boulders/:id/untick/:event_id/:user_id" => "boulders#untick"  
  match "/boulders/all" => "boulders#all"
  match "/boulders/todo" => "boulders#todo"
  match "/boulders/conquerored" => "boulders#conquerored"
  match "/boulders/:id/togglemod" => "boulders#togglemod"
  match "/boulders/:id/rate/:rating" => "boulders#rate", :constraints => { :rating => /.*/ }
  match "/boulders/:id/climbers" => "boulders#climbers"
  match "/boulders/:id/climbers/:compare_id" => "boulders#climbers"
  match "/boulders/:id/reporterror" => "boulders#report_error"
  match "/boulders/massedit" => "boulders#massedit"
  match "/boulders/lastweek" => "boulders#lastweek"

  match "/boulder_errors/:id/togglecheck" => "boulder_errors#togglecheck"

  match "/events/:id/boulders" => "events#boulders"
  match "/events/:id/rankings" => "rankings#index", :type => "event", :eventid => :id
  match "/events/active" => "events#active"
  match "/events/inactive" => "events#inactive"

  match "/rankings/:type" => "rankings#index"
  match "/rankings/event/:eventid" => "rankings#index", :type => "event"

  get "rankings_points" => "rankings#index", :type => "points"
  get "rankings_amount" => "rankings#index", :type => "amount"
  get "rankings_alltime" => "rankings#index", :type => "alltime"

  match "/users/register" => "users#register"
  match "/users/:id/resetpassword" => "users#resetpassword"
  match "/users/:id/chgpassword" => "users#chgpassword"
  match "/users/:id/compareto/:compare_id" => "users#compareto"
  
  match "/users/:id/reportdoubt/:boulderid" => "users#report_doubt"
  match "/boulder_doubts/:id/togglecheck" => "boulder_doubts#togglecheck"
  
  match "/index/showlocationselect" => "index#show_location_popup"
  match "/users/:user_id/saveLocationPreference/:location_id" => "users#save_location_preference"

  resources :sessions

  resources :events

  resources :boulders

  resources :boulder_errors
  
  resources :boulder_doubts

  resources :comments

  resources :colors

  resources :walls

  resources :locations

  resources :users

  resources :admin
  
  resources :options
  match "/options/save" => "options#save"

  get "edit_todo" => "users#new", :as => "edit_todo"
  get "boulders_done" => "users#new", :as => "boulders_done"

end

olddb/app/views/admin/_navigation.html.erb
<div class="navbar navbar-list navbar-inverse navbar-static-top navbar-functions"> 
	<div class="container-fluid">
        <div class="nav-collapse"> 
          <ul class="nav navbar-nav">
            <li class="dropdown <%=cp('/locations/new')%> <%=cp('/locations')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Standort <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/locations" %></li>
                    <li><%= link_to "Standort anlegen", "/locations/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown <%=cp('/walls/new')%> <%=cp('/walls')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Wände <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/walls" %></li>
                    <li><%= link_to "Wand anlegen", "/walls/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown <%=cp('/boulders/new')%> <%=cp('/boulders')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Boulder <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/boulders" %></li>
                    <li><%= link_to "Boulder anlegen", "/boulders/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown <%=cp('/events/new')%> <%=cp('/events')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Events <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/events" %></li>
                    <li><%= link_to "Event anlegen", "/events/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown <%=cp('/users/new')%> <%=cp('/users')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Benutzer <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/users" %></li>
                    <li><%= link_to "Benutzer anlegen", "/users/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class="dropdown <%=cp('/colors/new')%> <%=cp('/colors')%>">
                <a class="dropdown-toggle" data-toggle="dropdown" data-target="#" href="<%= "#{request.fullpath}" %>">Grifffarben <b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Übersicht", "/colors" %></li>
                    <li><%= link_to "Grifffarbe anlegen", "/colors/new" %></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
            <li class=""><%= link_to "Optionen", "/options" %></li>
          </ul>
        </div>
    </div>
</div>

olddb/app/views/admin/index.html.erb
<%= render 'admin/navigation' %>

<div class="container-fluid" style="margin-top: 30px">
	<div class="row">
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Standort</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Standorte anzeigen', :locations %></li>
					<li class="list-group-item"><%= link_to 'Standort anlegen', new_location_path %></li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Wände</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Wände anzeigen', :walls %></li>
					<li class="list-group-item"><%= link_to 'Wand anlegen', new_wall_path %></li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Boulder</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Boulder anzeigen', :boulders %></li>
					<li class="list-group-item"><%= link_to 'Boulder anlegen', new_boulder_path %></li>
				</ul>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">Events</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Events anzeigen', :events %></li>
					<li class="list-group-item"><%= link_to 'Event anlegen', new_event_path %></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">Benutzer</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Benutzer anzeigen', :users %></li>
					<li class="list-group-item"><%= link_to 'Benutzer anlegen', new_user_path %></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">Griffarben</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Grifffarben anzeigen', :colors %></li>
					<li class="list-group-item"><%= link_to 'Grifffarbe anlegen', new_color_path %></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">Optionen</div>
				<ul class="list-group">
					<li class="list-group-item"><%= link_to 'Optionen anzeigen', :options %></li>
				</ul>
			</div>
		</div>
	</div>
</div>