olddb/config/routes.rb
RoutenDb::Application.routes.draw do
  get "index/new"

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  match "/boulders/:id/showcomments" => "boulders#showcomments"

  root :to => "index#new"
  
  match "/boulders/:id/deactivate" => "boulders#deactivate"
  match "/boulders/:id/tick/:type/:event_id/:user_id" => "boulders#tick"
  match "/boulders/:id/untick/:event_id/:user_id" => "boulders#untick"  
  match "/boulders/all" => "boulders#all"
  match "/boulders/todo" => "boulders#todo"
  match "/boulders/conquerored" => "boulders#conquerored"
  match "/boulders/:id/togglemod" => "boulders#togglemod"
  match "/boulders/:id/rate/:rating" => "boulders#rate", :constraints => { :rating => /.*/ }
  match "/boulders/:id/climbers" => "boulders#climbers"
  match "/boulders/:id/climbers/:compare_id" => "boulders#climbers"
  match "/boulders/:id/reporterror" => "boulders#report_error"
  match "/boulders/massedit" => "boulders#massedit"
  match "/boulders/lastweek" => "boulders#lastweek"

  match "/boulder_errors/:id/togglecheck" => "boulder_errors#togglecheck"

  match "/events/:id/boulders" => "events#boulders"
  match "/events/:id/rankings" => "rankings#index", :type => "event", :eventid => :id
  match "/events/active" => "events#active"
  match "/events/inactive" => "events#inactive"

  match "/rankings/:type" => "rankings#index"
  match "/rankings/event/:eventid" => "rankings#index", :type => "event"

  get "rankings_points" => "rankings#index", :type => "points"
  get "rankings_amount" => "rankings#index", :type => "amount"
  get "rankings_alltime" => "rankings#index", :type => "alltime"

  match "/users/register" => "users#register"
  match "/users/:id/resetpassword" => "users#resetpassword"
  match "/users/:id/chgpassword" => "users#chgpassword"
  match "/users/:id/compareto/:compare_id" => "users#compareto"
  
  match "/users/:id/reportdoubt/:boulderid" => "users#report_doubt"
  match "/boulder_doubts/:id/togglecheck" => "boulder_doubts#togglecheck"
  
  match "/index/showlocationselect" => "index#show_location_popup"
  match "/users/:user_id/saveLocationPreference/:location_id" => "users#save_location_preference"

  resources :sessions

  resources :events

  resources :boulders

  resources :boulder_errors
  
  resources :boulder_doubts

  resources :comments

  resources :colors

  resources :walls

  resources :locations

  resources :users

  resources :admin
  
  resources :options
  match "/options/save" => "options#save"

  get "edit_todo" => "users#new", :as => "edit_todo"
  get "boulders_done" => "users#new", :as => "boulders_done"

end

olddb/app/models/boulder.rb
class Boulder < ActiveRecord::Base
  attr_accessible :climbers, :color_id, :description, :disable_date, :level_intern, :level_public, :manual_modified, :name, :points, :rating, :remove_date, :status, :votes, :wall_from, :wall_to, :creator_ids, :rating_count

  belongs_to :color
  belongs_to :wallfrom, :class_name => "Wall", :foreign_key => :wall_from
  belongs_to :wallto, :class_name => "Wall", :foreign_key => :wall_to

  has_many :boulder_creators
  has_many :creators, :source => :user, :through => :boulder_creators

  has_many :boulder_conquerors
  has_many :conquerors, :source => :user, :through => :boulder_conquerors

  has_many :comments

  has_many :event_boulders
  has_many :events, :through => :event_boulders

  validates :name, :presence => true
  validates :color_id, :presence => true
  validates :level_intern, :presence => true
  validates :level_public, :presence => true
  validates :creator_ids, :presence => true

  def is_mod
    if self.manual_modified.nil?
      return false
    end

    if self.manual_modified >= 1.week.ago
      return true
    end

    return false
  end


  def set_mod
    self.manual_modified = Time.now
    self.save
  end


  def remove_mod
    self.manual_modified = nil
    self.save
  end


  def deactivate
    self.status = 0
    self.remove_date = Time.now
    self.save
  end


  def get_location
    unless self.wall_from == nil
      location = Location.find(self.wallfrom.location.id)
      return location
    end
    unless self.wall_to == nil
      location = Location.find(self.wallto.location.id)
      return location
    end
  end
end

olddb/app/controllers/boulders_controller.rb
class BouldersController < ApplicationController

  skip_before_filter :require_admin, :only=> [:index, :showcomments, :show, :tick, :untick, :todo, :conquerored, :lastweek, :rate, :climbers, :report_error]

  # GET /boulders
  # GET /boulders.json
  def index
	walls = get_walls_for_location(get_location)
    @boulders = Boulder.where('status = ? and (wall_from in (?) or wall_to in (?))', 1, walls, walls).includes(:creators).includes(:events).includes(:color).includes(:wallfrom).includes(:wallto).order('level_public, created_at DESC')
    
    if params[:filter] == 'event'
      @boulders = @boulders.find_all{ |boulder| boulder.events.where('events.id = ?', params[:event_id]).size == 1 }
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boulders }
    end
  end

  # GET /boulders/all
  # GET /boulders/all.json
  def all
	walls = get_walls_for_location(get_location)
    @boulders = Boulder.where('(wall_from in (?) or wall_to in (?))', walls, walls).includes(:creators).includes(:events).includes(:color).includes(:wallfrom).includes(:wallto).order('level_public, created_at DESC')
    if params[:filter] == 'event'
      @boulders = @boulders.find_all{ |boulder| boulder.events.where('events.id = ?', params[:event_id]).size == 1 }
    end
    render 'boulders/index'
  end

  # GET /boulders/lastweek
  # GET /boulders/lastweek.json
  def lastweek
	walls = get_walls_for_location(get_location)
    @boulders = Boulder.where('created_at >= ? AND status = ? and (wall_from in (?) or wall_to in (?))', 1.week.ago, 1, walls, walls).includes(:creators).includes(:events).includes(:color).includes(:wallfrom).includes(:wallto).order('level_public, created_at DESC')
    render 'boulders/index'
  end

  # GET /boulders/todo
  # GET /boulders/todo.json
  def todo
	walls = get_walls_for_location(get_location)
    boulders = Boulder.where('status = ? and (wall_from in (?) or wall_to in (?))', 1, walls, walls).includes(:creators).includes(:events).includes(:color).includes(:wallfrom).includes(:wallto).order('level_public, created_at DESC')
    boulders_c = Boulder.joins(:boulder_conquerors).where('status = ? AND user_id = ?', 1, current_user.id).includes(:creators).includes(:color).includes(:wallfrom).includes(:wallto).order('level_public, created_at DESC').group('boulders.id')
    @boulders = boulders - boulders_c

    if params[:filter] == 'event'
      @boulders = @boulders.find_all{ |boulder| boulder.events.where('events.id = ?', params[:event_id]).size == 1 }
    end

    render 'boulders/index'
  end

  # GET /boulders/conquerored
  # GET /boulders/conquerored.json
  def conquerored
	walls = get_walls_for_location(get_location)
    @boulders = Boulder.joins(:boulder_conquerors)
                      .where("status = ? AND user_id = ? and type != 'flash-doubt' and type != 'top-doubt' and (wall_from in (?) or wall_to in (?))", 1, current_user.id, walls, walls)
                      .includes(:creators)
                      .includes(:events)
                      .includes(:color)
                      .includes(:wallfrom)
                      .includes(:wallto)
                      .order('level_public, created_at DESC')
                      .group('boulders.id')

    if params[:filter] == 'event'
      @boulders = @boulders.find_all{ |boulder| boulder.events.where('events.id = ?', params[:event_id]).size == 1 }
    end

    render 'boulders/index'
  end

  # GET /boulders/1
  # GET /boulders/1.json
  def show
    @boulder = Boulder.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => false }# show.html.erb
      format.json { render json: @boulder }
    end
  end

  # GET /boulders/1/showcomments
  # GET /boulders/1/showcomments.json
  def showcomments
    @comments = Boulder.find(params[:id], :order => "created_at DESC").comments
    @boulder_id = params[:id]
    render 'comments/list', :layout => false
  end

  # GET /boulders/new
  # GET /boulders/new.json
  def new
    @is_new = true
    @boulder = Boulder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boulder }
    end
  end

  # GET /boulders/1/edit
  def edit
    @is_new = false
    @boulder = Boulder.find(params[:id])
  end

  # POST /boulders
  # POST /boulders.json
  def create
    @boulder = Boulder.new(params[:boulder])
    
    points = get_option('boulder_default_points')
    if points.nil?
    	points = 1000
    end
    
    @boulder.points = points
    
    respond_to do |format|
      if @boulder.save
        if params[:boulder_form_save_and_new]
          @boulder2 = Boulder.new
          format.html { redirect_to "/boulders/new" }
          format.json { render json: @boulder2 }
        else 
          format.html { redirect_to boulders_path, notice: 'Boulder was successfully created.' }
          format.json { render json: @boulder, status: :created, location: @boulder }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @boulder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boulders/1
  # PUT /boulders/1.json
  def update
    @boulder = Boulder.find(params[:id])
    respond_to do |format|
      if @boulder.update_attributes(params[:boulder])
        if params[:boulder_form_save_and_new]
          @boulder2 = Boulder.new
          format.html { redirect_to "/boulders/new" }
          format.json { render json: @boulder2 }
        else 
          format.html { redirect_to boulders_path, notice: 'Boulder was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @boulder.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /boulders/1/deactivate
  def deactivate
    boulder = Boulder.find(params[:id])
    boulder.deactivate
    redirect_to :boulders
  end

  # GET /boulders/1/tick/top/1
  # GET /boulders/:boulder_id/tick/top/:user_id
  def tick
    if current_user.is_admin? and params[:user_id]
      user_id = params[:user_id]
    else
      user_id = current_user.id
    end

    # Immer in allen Events in denen die Route verwendet wird abhaken und auch mit event id 0 abhaken, egal wo man abgehakt hat.
    events = Event.joins(:event_boulders).where('boulder_id = ?', params[:id])
    events.each do |event|
      if event.is_active
	  	ticked = BoulderConqueror.where({:boulder_id => params[:id], :event_id => event.id, :user_id => user_id}).first()
		if ticked
			ticked.type = params[:type]
		else
			ticked = BoulderConqueror.create({:boulder_id => params[:id], :event_id => event.id, :type => params[:type], :user_id => user_id})
		end
        ticked.save
      end
    end

	ticked = BoulderConqueror.where({:boulder_id => params[:id], :event_id => 0, :user_id => user_id}).first()
	
	if ticked
		# auch den status in der anzweifeln liste checken
		@doubt = BoulderDoubt.where("user_id = ? AND boulder_id = ?", user_id, params[:id]).first()
		if !@doubt.nil?
			@doubt.status = 1
			@doubt.save
			ticked.type = params[:type]
		end
	else
		ticked = BoulderConqueror.create({:boulder_id => params[:id], :event_id => 0, :type => params[:type], :user_id => user_id})    
	end
    ticked.save

    # LastActivity setzen
    if current_user.id.to_s == params[:user_id] or !params[:user_id]
      current_user.last_activity = Time.now
      current_user.save
    end

    # Punktezahl ermitteln und zurückgeben
    if params[:event_id] != '0'
      @event = Event.find(params[:event_id])
    end

	#### wird nicht mehr asynchron gemacht, sondern so wie früher direkt beim Aufruf des Rankings #####
	# AsyncWorker.updateRanking(logger)
    @boulder = Boulder.find(params[:id])
    respond_to do |format|
      format.html { render json: render_points(@boulder, true) }
    end

  end

  # GET /boulders/1/untick/9
  # GET /boulders/:boulder_id/untick/:user_id
  def untick

    if current_user.is_admin? and params[:user_id]
      user_id = params[:user_id]
    else
      user_id = current_user.id
    end

    # Event ID nicht beachtenm da immer alle Haken entfernt werden sollen
    BoulderConqueror.where("boulder_id = ? AND user_id = ?", params[:id], user_id).destroy_all

    # LastActivity setzen
    if current_user.id.to_s == params[:user_id] or !params[:user_id]
      current_user.last_activity = Time.now
      current_user.save
    end

    # Punktezahl ermitteln und zurückgeben
    if params[:event_id] != '0'
      @event = Event.find(params[:event_id])
	end

	#### wird nicht mehr asynchron gemacht, sondern so wie früher direkt beim Aufruf des Rankings #####
	# AsyncWorker.updateRanking(logger)
    @boulder = Boulder.find(params[:id])
    respond_to do |format|
      format.html { render json: render_points(@boulder, true) }
    end
  end

  # GET /boulders/1/togglemod
# Wurde durch die Massenbearbeitung ersetzt
#  def togglemod
#    boulder = Boulder.find(params[:id])
#    if boulder.manual_modified == nil
#      boulder.manual_modified = Time.now
#    else
#      boulder.manual_modified = nil
#    end
#    boulder.save#
#    return render_tags(boulder)
#  end

  # GET /boulders/1/rate/5
  def rate
    rating = BoulderRating.find_or_initialize_by_boulder_id_and_user_id(:boulder_id => params[:id], :user_id => current_user.id)
    rating.update_attribute(:rating, params[:rating])

    # Ranking neu berechnen
    ActiveRecord::Base.connection.execute('
      UPDATE boulders b SET rating = (SELECT (CASE WHEN COUNT(rating) > 0 THEN SUM(rating) / COUNT(rating) ELSE 0 END) as rating FROM boulder_ratings WHERE boulder_id = b.id),
                            rating_count = (SELECT COUNT(rating) as rating_count FROM boulder_ratings WHERE boulder_id = b.id);');

    boulder = Boulder.find(params[:id])

    render :text => boulder.rating
  end


  # GET /boulders/1/climbers
  def climbers
    @boulder = Boulder.find(params[:id])

olddb/app/helpers/boulders_helper.rb
module BouldersHelper
	
	def render_wall(boulder)
		output = ''
		if boulder.wallfrom.nil?
			unless boulder.wallto.nil?
				output = link_to boulder.wallto.name, boulder.wallto, {:class => "show", :title => boulder.wallto.name}
			end
		else
			if boulder.wallto.nil?
				output = link_to boulder.wallfrom.name, boulder.wallfrom, {:class => "show", :title => boulder.wallfrom.name}
			else
				if boulder.wallfrom.id == boulder.wallto.id
					output = link_to boulder.wallfrom.name, boulder.wallfrom, {:class => "show", :title => boulder.wallfrom.name}
				else
					output = (link_to boulder.wallfrom.name, boulder.wallfrom, {:class => "show", :title => boulder.wallfrom.name}) + " => " + (link_to boulder.wallto.name, boulder.wallto, {:class => "show", :title => boulder.wallto.name})
				end
			end
		end
		output
	end
	

	# render_captured in application_helper verlegt

	def render_comments(boulder)
		if boulder.comments.size == 0
			link_to image_tag("comments_white.png"), "/boulders/"+boulder.id.to_s+"/showcomments", {:class => "icon comments-link", :title => boulder.name}
		else
			link_to image_tag("comments.png"), "/boulders/"+boulder.id.to_s+"/showcomments", {:class => "icon comments-link", :title => boulder.name}
		end
	end
	

	def get_levels_internal(locationID = nil)
		max_level = get_option('levels_internal', locationID)

		if max_level.nil?
			max_level = '7'
		end

		levels = []
		max_level.to_i.times { |i| levels.push(i + 1) }

		return levels
	end
	

	def get_levels_external(locationID = nil)
		max_level = get_option('levels_external', locationID)

		if max_level.nil?
			max_level = '7'
		end

		levels = []
		max_level.to_i.times { |i| levels.push(i + 1) }

		return levels
	end
	

	def get_level_icon(level)
		defaultIcon = "levels/#{level}.png"
		locationIcon = "levels/#{get_locationID()}/#{level}.png"
		
		if Rails.application.assets.find_asset locationIcon
			return locationIcon
		end
		
		return defaultIcon
	end

end

olddb/app/views/boulders/_form.html.erb
<% location = get_location %>

<%= semantic_form_for(@boulder) do |f| %>
  <% if @boulder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boulder.errors.count, "error") %> prohibited this boulder from being saved:</h2>

      <ul>
      <% @boulder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <%= f.input :name, :required => true %>
    <%= f.input :level_intern, :required => true, :as => :select, :collection => get_levels_internal(), :label => 'Level (intern)' %>
    <%= f.input :level_public, :required => true, :as => :select, :collection => get_levels_external(), :label => 'Level' %>
    <%= f.input :color_id, :required => true, :as => :select, :collection => Color.find(:all, :order => :name), :label => 'Grifffarbe' %>
    <% if @is_new == false %>
      <%= f.input :points, :label => 'Punkte' %>
      <%= f.input :status, :as => :boolean, :label => 'Aktiv' %>
    <% else %>
      <%= f.input :points, :as => :hidden, :label => 'Punkte' %>
      <%= f.input :status, :as => :hidden, :input_html => { :value => "1" }, :label => 'Aktiv' %>
    <% end %>
    <%= f.input :wall_from, :as => :select, :collection => Wall.where('location_id = ?', location.id).order(:name), :label => 'Wand von' %>
    <%= f.input :wall_to, :as => :select, :collection => Wall.where('location_id = ?', location.id).order(:name), :label => 'Wand bis' %>
    <%= f.input :creators, :as => :select, :required => true, :collection => User.where('is_creator = ?', true).order(:username), :label => 'Schrauber' %>
  <% end %>

  <%= f.actions do %>
      <%= f.action :submit, :as => :button, :button_html => { :name => 'boulder_form_save' }, :label => "Speichern" %>
      <%= f.action :submit, :as => :button, :button_html => { :name => 'boulder_form_save_and_new' }, :label => "Speichern und Neu" %>
  <% end %>

<% end %>

olddb/app/views/boulders/_list.html.erb
<table id="boulders" class="display">
	<thead>
		<tr>
			<th title="Geschafft / Nicht geschafft"></th>
			<th title="Level">L</th>
			<th title="Level (intern)" <%= is_admin?? "" : 'class=hide' %>>L</th>
			<th class="hide">Punkte for sorting</th>
			<th title="Punkte (Anzahl Begeher)">Punkte</th>
			<th>Tags</th>
			<th>Events</th>
			<th>Wand (von => nach)</th>
			<th>Farbe</th>
			<th>Name</th>
			<th>Schrauber</th>
			<th class="hide">Rating for sorting</th>
			<th>Rating</th>
			<th class="hide">Created for sorting</th>
			<th>Created</th>
			<th title="Kommentare"></th>
			<th <%= is_admin?? "" : 'class=hide' %>></th>
			<th <%= is_admin?? "" : 'class=hide' %>></th>
			<th <%= is_logged_in?? "" : 'class=hide' %>></th>
			<th <%= is_admin?? "" : 'class=hide' %>></th>
		</tr>
	</thead>

	<tbody>
		<% @boulders.each do |boulder| %>
		<% @ownRating = current_user.nil? ? nil : BoulderRating.where(:boulder_id => boulder.id, :user_id => current_user.id).first
		   @ownRatingText = @ownRating.nil? ? 'Ich habe diese Route noch nicht bewertet.' : 'Meine eigene Wertung: ' + @ownRating.rating.to_s
		%>
			<tr class="<%= is_doubt(boulder) ? "doubt" : "" %>">
				<td class="center"><%= render_captured(boulder) %></td>
				<td class="center"><%= image_tag get_level_icon(boulder.level_public) %></td>
				<td class="center"><%= image_tag get_level_icon(boulder.level_intern) %></td>
				<td><%= render_points(boulder, false) %></td>
				<td><%= link_to render_points(boulder, true), '/boulders/'+boulder.id.to_s+'/climbers', {:id => "boulder_points_"+boulder.id.to_s, :class => 'show-climbers'} %></td>
				<td id="boulder_tags_<%= boulder.id %>"><%= raw render_tags(boulder) %></td>
				<td><%= raw render_eventlogos(boulder) %></td>
				<td><%= render_wall(boulder) %></td>
				<td><%= boulder.color.nil?? "" : (boulder.color.icon_url ? (image_tag boulder.color.icon_url.to_s, :size => '16x16', :title => boulder.color.name) : '') + ' ' +boulder.color.name %></td>
				<td><%= link_to boulder.name, boulder, {:class => "show", :title => boulder.name } %></td>
				<td><%= boulder.creators.map{ |creator| creator.username }.join(", ") %></td>
				<td><%= boulder.rating %></td>
				<td class="rating-cell">
					<div class="rating" boulder-id="<%= boulder.id %>" data-rating="<%= boulder.rating %>" data-count="<%= boulder.rating_count %>" title="Score: <%= boulder.rating %> / <%= boulder.rating_count.nil?? '0' : boulder.rating_count.to_s %> User <%= !boulder.rating_count.nil? && boulder.rating_count != 1 ? 'haben' : 'hat' %> diese Route bewertet. <%= @ownRatingText %>"></div>
					<% if @ownRating != nil %>
						<%= image_tag("bullet_valid.png", {:class => 'my-rating', :title => @ownRatingText }) %>
					<% end %>
				</td>
				<td><%= boulder.created_at %></td>
				<td><%= format_date(boulder.created_at, nil) %></td>
				<td><%= render_comments(boulder) %></td>
				<td><%= link_to image_tag("edit.png", {:title => 'Bearbeiten'}), edit_boulder_path(boulder), {:class => "icon edit"} %></td>
				<td><%= link_to image_tag("delete.png", {:title => 'Deaktivieren'}), "/boulders/"+boulder.id.to_s+"/deactivate", {:class => "icon delete"}, data: { confirm: 'Are you sure?'} %></td>
				<td><%= link_to image_tag("exclamation.png"), "/boulders/"+boulder.id.to_s+"/reporterror", {:class => "icon delete error-link", :title => "Fehler melden"} %></td>
				<td><input type="checkbox" name="massedit" value="<%= boulder.id %>"/></td>
			</tr>
		<% end %>
	</tbody>
</table>

olddb/app/views/boulders/_report_error.html.erb
<% if(current_user) %>

	<h3>Fehler zu Route <%= @boulder_name%> melden</h3>
	<div class="field">
		<textarea id="error_for_<%= @boulder_id %>"></textarea>
	</div>
	<div class="actions">
		<a class="btn btn-info" href="javascript:submitErrorReport(<%= @boulder_id %>, <%= current_user.id %>)">Fehler melden</a>
	</div>

<% end %>

olddb/app/views/boulders/_tick-popup.erb
<div id="tick-popup" style="display: none;">
	<span>Top or Flash?<span><%= link_to "X", "/boulders", {:id => "close-tick-popup"} %></span></span>
	<ul>
		<li><%= link_to "Top", "/boulders", {:id => "tick-top"} %></li>
		<li><%= link_to "Flash (+10%)", "/boulders", {:id => "tick-flash"} %></li>
	</ul>
</div>

olddb/app/views/boulders/index.html.erb
<div class="navbar navbar-list navbar-inverse navbar-static-top navbar-functions"> 
    <div class="container-fluid">
        <div class="nav-collapse"> 
			<ul class="nav navbar-nav">
				<% if is_admin? %>
					<li><%= link_to 'Route anlegen', new_boulder_path %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to 'Alle Routen (inkl. inaktive)', '/boulders/all' %></li>
				<% end %>
				<% if current_user %>
					<li class="divider-vertical"></li>
				<% end %>
			</ul>
			<form class="navbar-form navbar-left">
				<div class="form-group">
					Meine Leistung vergleichen mit:
					<%= render_compare_select() %>
				</div>
			</from>
			<p id="table_filter_placeholder" class="navbar-text navbar-right"></p>
        </div>
    </div>
</div>

<p id="notice"><%= notice %></p>

<%= render 'boulders/list' %>

<%= render 'boulders/tick-popup' %>

olddb/app/views/boulders/show.html.erb
<p id="notice"><%= notice %></p>

<table class="show-data">
  <tr class="odd">
    <td class="label">Name:</td>
    <td class="value"><%= @boulder.name %></td>
  </tr>
  <% if is_admin? %>
    <tr class="even">
      <td class="label">Level (nur intern):</td>
      <td class="value"><%= image_tag get_level_icon(@boulder.level_intern) %> (<%= @boulder.level_intern %>)</td>
    </tr>
  <% end %>
  <tr class="even">
    <td class="label">Level:</td>
    <td class="value"><%= image_tag get_level_icon(@boulder.level_public) %> (<%= @boulder.level_public %>)</td>
  </tr>
  <tr class="odd">
    <td class="label">Farbe:</td>
    <td class="value"><%= @boulder.color.nil?? "" : (@boulder.color.icon_url ? (image_tag @boulder.color.icon_url.to_s, :size => '16x16', :title => @boulder.color.name) : @boulder.color.name) %></td>
  </tr>
  <tr class="even">
    <td class="label">Punkte:</td>
    <td class="value"><%= @boulder.points %></td>
  </tr>
  <tr class="odd">
    <td class="label">Status:</td>
    <td class="value"><%= @boulder.status %></td>
  </tr>
  <tr class="even">
    <td class="label">Entfert am:</td>
    <td class="value"><%= format_date(@boulder.remove_date, nil) %></td>
  </tr>
  <tr class="odd">
    <td class="label">Bewertungen (Anzahl):</td>
    <td class="value"><%= @boulder.rating_count.nil?? '0' : @boulder.rating_count.to_s %></td>
  </tr>
  <tr class="even">
    <td class="label">Bewertung:</td>
    <td class="value"><%= @boulder.rating %></td>
  </tr>
  <tr class="odd">
    <td class="label">Begeher (Anzahl):</td>
    <td class="value"><%= @boulder.boulder_conquerors.where('event_id = ?', 0).size.to_s %></td>
  </tr>
  <tr class="even">
    <td class="label">Modifiziert am:</td>
    <td class="value"><%= format_date(@boulder.manual_modified, nil) %></td>
  </tr>
  <tr class="odd">
    <td class="label">Deaktiviert am:</td>
    <td class="value"><%= format_date(@boulder.disable_date, nil) %></td>
  </tr>
  <tr class="even">
    <td class="label">Wand von:</td>
    <td class="value">
      <%=
        if @boulder.wallfrom.nil?
          puts "-"
        else
          @boulder.wallfrom.name
        end
      %>
    </td>
  </tr>
  <tr class="odd">
    <td class="label">Wand bis:</td>
    <td class="value">
      <%=
        if @boulder.wallto.nil?
          puts "-"
        else
          @boulder.wallto.name
        end
      %>
    </td>
  </tr>
  <tr class="even">
    <td class="label">Standort:</td>
    <td class="value"><%= @boulder.get_location.name %></td>
  </tr>
  <tr class="odd">
    <td class="label">Schrauber:</td>
    <td class="value">
      <%= @boulder.creators.map{ |creator| creator.username }.join(", ") %>
    </td>
  </tr>
</table>

<% if is_admin? %>
  <%= link_to 'Edit', edit_boulder_path(@boulder), {:class => "edit btn btn-info"} %>
<% end %>